
# Ref1, [HOW-TO build image](https://yeasy.gitbooks.io/docker_practice/image/build.html)
# Ref2, [Dockerfile Ref](https://docs.docker.com/engine/reference/builder/)

FROM scratch

ARG WAZUH_AGENT_VERSION=3.9.1-2

ENV random="" \
    random2=""

ARG TEMPLATE_VERSION="v3.9.1"

# Set repositories
RUN apt-get install curl apt-transport-https lsb-release gnupg2 && \
    curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add - && \
    echo "deb https://packages.wazuh.com/3.x/apt/ stable main" | tee /etc/apt/sources.list.d/wazuh.list && \
    apt-get update && \
    ## HARDCODED VARIABLE
    WAZUH_MANAGER_IP="10.0.0.2" apt-get install wazuh-agent

# Adding 
