
# Ref1, [HOW-TO build image](https://yeasy.gitbooks.io/docker_practice/image/build.html)
# Ref2, [Dockerfile Ref](https://docs.docker.com/engine/reference/builder/)
# Ref3, [Configure a Pod to Use a ConfigMap](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/)
# Ref4, [在 Pod 里使用 ConfigMap 数据](https://k8smeetup.github.io/docs/tasks/configure-pod-container/configure-pod-configmap/)
# Ref5, [Wazuh3.9Doc-UM-regiAgents-UsingAPI](https://documentation.wazuh.com/3.9/user-manual/registering/restful-api-register.html#restful-api-register)

# A minimal Ubuntu base image
FROM phusion/baseimage:latest

# ARG WAZUH_AGENT_VERSION=3.9.1-2

# ENV random="" \
#     random2=""

# ARG TEMPLATE_VERSION="v3.9.1"

# Set repositories
RUN apt-cache search gnupg2 && apt-get update && \
    apt-get install -y curl apt-transport-https lsb-release gnupg2 && \
    curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add - && \
    echo "deb https://packages.wazuh.com/3.x/apt/ stable main" | tee /etc/apt/sources.list.d/wazuh.list && \
    apt-get update && \
    ## HARDCODED VARIABLE
    WAZUH_MANAGER_IP="10.0.0.2" apt-get install -y wazuh-agent && \
    # apt-get install wazuh-agent && \
    # disable wazuh-agent update
    sed -i "s/^deb/#deb/" /etc/apt/sources.list.d/wazuh.list && \
    apt-get update

# Register Agent
# Sync calls are due to https://github.com/docker/docker/issues/9547

# COPY config/api-register-agent.sh /api-register-agent.sh
# RUN chmod 755 /api-register-agent.sh && \
#     sync && /api-register-agent.sh

# It seems no need to create volume for config.
# VOLUME ["/var/ossec/etc"]

